cloud:
  aws:
    region:
      static: us-west-2
      auto: false
    credentials:
      access-key: AKIA3HLW7PCZO7G4MP5M
      secret-key: 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
    end-point:
      uri: https://sqs.us-west-2.amazonaws.com/771733026994/kailash-queue
    end-point-2:
        uri: https://sqs.us-west-2.amazonaws.com/771733026994/kailash-queue-2